### ISSUE TITLE
Failed tests due to missing packages

### ISSUE THREAD

**Issue by abhigenie92** [AmmsA/django-resumator#7]
```
abhishek django-resumator-master $ python runtests.py 
Traceback (most recent call last):
  File "runtests.py", line 11, in <module>
    django.setup()
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/abhishek/anaconda3/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/abhishek/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/abhishek/Desktop/code/website/django-resumator-master/resumator/models.py", line 6, in <module>
    from colorful.fields import RGBColorField
ImportError: No module named 'colorful'
```

**Comment by ammsa** [comment]
Did you install the required packages? 
In the same directory, do `pip install -r requirements.txt`. By the way, I've developed this app with `python2.7`, it looks like your using `python3.5`. I haven't tested this app with python3. I suggest using python2.

**Comment by abhigenie92** [comment]
Thanks! After that it works well with python2.

**Comment by ammsa** [comment]
Cheers!
